import localFont from "next/font/local"; 
import "./globals.css";

const iosevkaCharon = localFont({
  src: [
    {
      path: "./fonts/IosevkaCharon-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/IosevkaCharon-LightItalic.ttf",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/IosevkaCharon-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/IosevkaCharon-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/IosevkaCharon-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/IosevkaCharon-MediumItalic.ttf",
      weight: "500",
      style: "italic",
    },
    {
      path: "./fonts/IosevkaCharon-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/IosevkaCharon-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-iosevka",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 return (
  <html lang="en">
    <body className={iosevkaCharon.variable}> 
      <main className="font-sans min-h-full flex flex-col">
        {children}
      </main>
    </body>
  </html>
);
}